### PR TITLE
Spec attributes fix and readthedocs fix (#219, #231, #223)

### PR DESCRIPTION
**Pull request by LukasSlouka**
I feel something fishy about the changes in `doc/conf.py` fix. I am not completely sold on mocking all those modules and suspect that there is more elegant workaround. However it fixed the problem and did not cause any more additional problems, but I will try to give it more time. Also the spec attributes refactor seemed to solve other problems that @cibo94 had.

### CODE REVIEW

**Comment by cibo94** [comment]
https://github.com/LukasSlouka/rpg/commit/81e55ac59ced96c2d800b5addcdb5c8e388a0e92 will fix also #223

**Comment by jsilhan** [comment]
Great, you did good job. Please fix the PEP8 violations:
```
Found violations: doc/conf.py

W292 @ 68:2 - no newline at end of file

Found violations: rpg/spec.py

E261 @ 49:23 - at least two spaces before inline comment

E261 @ 50:26 - at least two spaces before inline comment

E261 @ 51:26 - at least two spaces before inline comment

E261 @ 52:26 - at least two spaces before inline comment

E261 @ 53:24 - at least two spaces before inline comment

E261 @ 54:26 - at least two spaces before inline comment

E261 @ 55:22 - at least two spaces before inline comment

E261 @ 56:25 - at least two spaces before inline comment

E261 @ 57:24 - at least two spaces before inline comment

E261 @ 58:28 - at least two spaces before inline comment

E261 @ 59:28 - at least two spaces before inline comment

E261 @ 60:28 - at least two spaces before inline comment

E261 @ 61:28 - at least two spaces before inline comment

E261 @ 62:25 - at least two spaces before inline comment

E261 @ 63:27 - at least two spaces before inline comment

E261 @ 64:26 - at least two spaces before inline comment

E261 @ 65:30 - at least two spaces before inline comment

E261 @ 66:35 - at least two spaces before inline comment

E261 @ 67:30 - at least two spaces before inline comment

E261 @ 68:30 - at least two spaces before inline comment

E261 @ 69:24 - at least two spaces before inline comment

E261 @ 70:28 - at least two spaces before inline comment

E261 @ 71:30 - at least two spaces before inline comment

E261 @ 72:31 - at least two spaces before inline comment

E261 @ 73:29 - at least two spaces before inline comment

E261 @ 74:33 - at least two spaces before inline comment

E261 @ 75:31 - at least two spaces before inline comment

E261 @ 76:30 - at least two spaces before inline comment

E261 @ 77:31 - at least two spaces before inline comment

E261 @ 78:32 - at least two spaces before inline comment

E261 @ 79:34 - at least two spaces before inline comment

E261 @ 80:35 - at least two spaces before inline comment

E261 @ 81:31 - at least two spaces before inline comment
```

**Comment by LukasSlouka** [comment]
Fixed, I apologize for those

**Comment by jsilhan** [comment]
Merged, thanks

**Pull request merged**
