### PR TITLE
Issue93

### PR DESCRIPTION
**Pull request by regeciovad**

### CODE REVIEW

**Comment by jsilhan** [comment]
Great patch, this should really improve UX for users. Fix my comments, please.

**Comment by regeciovad** [comment]
Fixed. Just one question: First page looks now a little bit weird.
What would be better - make this page smaller, or make space between rows bigger?

**Comment by jsilhan** [comment]
Lets leave it as it is. We can add there some trext later

**Comment by jsilhan** [comment]
Good job, merged, thanks

**Pull request merged**
