### PR TITLE
Prefil of the mandatory page + maven unit test (fix #295)

### LINKED ISSUE #295: UX: prefill the spec.Name, version, ... what can be found by project builder plugins
- [ ] maven plugin
- [ ] cmake plugin
- [ ] autotools
- [ ] setuptools
- [ ] document `extracted` plugin phase that it could change Spec required fields and in other methods it's forbidden to do that. - add it as some yellow / blue notice, please

It should be added to spec in `extracted` method

depends on #280 for fully working but can be implemented simultaneously

### PR DESCRIPTION
**Pull request by LukasSlouka**
I did not document extracted phase yet (i think it could be put into separate issue with *doc* label).

As the `Mandatory page` was split into two parts, the `Summary page` did not "inherit" the prefillment behavior. Summary page may as well be prefilled, the code I pushed already does it.

### CODE REVIEW

**Comment by LukasSlouka** [comment]
Rebased and merge conflicts resolved

**Comment by LukasSlouka** [comment]
This bugs some tests, prefill needs refactor

**Comment by LukasSlouka** [comment]
Fixed

**Comment by jsilhan** [comment]
Merged, thanks

**Pull request merged**
