### PR TITLE
Changed long test in all project to connection test

### PR DESCRIPTION
**Pull request by yousifd**
Issue #329

### CODE REVIEW

**Comment by jsilhan** [comment]
Merged, thanks. (I squashed the commits). Btw who are you and how you got to know about RPG project?

**Comment by yousifd** [comment]
Hello, I am a freshman CS student and I am looking into learning more about open source and have been going around look for simple stuff to do and learn through that.

Could you tell me how did you squashed the commits? and why did you do that?

**Comment by jsilhan** [comment]
That was good job. I have you can take more easy stuff https://github.com/rh-lab-q/rpg/labels/easy . Tell me if you need guidance or more explanation of the tasks.

> Could you tell me how did you squashed the commits?

`git rebase -i HEAD~5` - learn more about the powerful interactive rebase command - it can reorder, squash and rename previous commits

> and why did you do that?

To have cleaner commit history - one commit - one issue (if it's not too complex)

**Comment by jsilhan** [comment]
I even added - `(fix #<fixed_issue>)` into commit message, so the issue will be automatically closed when merged.

@yousifd feel free to contact me via mail. We can find you the issues where you can progress. I could choose among more projects I deal with: https://github.com/rpm-software-management/dnf , https://github.com/rpm-software-management/hawkey , https://github.com/rpm-software-management/dnf-plugins-core or https://github.com/rpm-software-management/dnf-plugins-extras

**Comment by yousifd** [comment]
Thanks for answering my questions and providing all of these suggestions. I will definitely contact you if I need any guidance or support.

**Pull request closed without merging**
