### PR TITLE
Mock waiter repair

### PR DESCRIPTION
**Pull request by cibo94**

### CODE REVIEW

**Comment by cibo94** [comment]
```bash
$ git clone --depth=50 git://github.com/rh-lab-q/rpg.git rh-lab-q/rpg
Cloning into 'rh-lab-q/rpg'...
remote: Counting objects: 357, done.
remote: Compressing objects: 100% (181/181), done.
remote: Total 357 (delta 201), reused 295 (delta 164), pack-reused 0
Receiving objects: 100% (357/357), 85.92 KiB | 0 bytes/s, done.
Resolving deltas: 100% (201/201), done.
Checking connectivity... done.

$ cd rh-lab-q/rpg/

$ git fetch origin +refs/pull/195/merge
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 4), reused 2 (delta 1), pack-reused 0
Unpacking objects: 100% (6/6), done.
From git://github.com/rh-lab-q/rpg
 * branch            refs/pull/195/merge -> FETCH_HEAD

$ git checkout -qf FETCH_HEAD

$ git describe --match=rpg-0.0.1-1 40482e8a2cf58a0c2375cdaef86169e571fa72b4
fatal: No names found, cannot describe anything.

$ git describe --match=rpg-0.0.1-1 0e60112425145a2f9e8bc252c984fbc2b822e2bfgit
fatal: No names found, cannot describe anything.

$ git describe --match=rpg-0.0.1-1
fatal: No names found, cannot describe anything.

$ git describe --match=rpg-0.0.1-1 HEAD
fatal: No names found, cannot describe anything.
```

**Comment by cibo94** [comment]
This problem as I found out start right after my last pull request (#186) was merged. Any idea why?

**Comment by jsilhan** [comment]
@cibo94 can you find the exact commit hash which caused the regression?

**Comment by cibo94** [comment]
c0f9e8a9eb4fedfa1d41cbe1b41bc33a937ee62f this should be it

**Comment by jsilhan** [comment]
still the tito in travis fails, see https://github.com/rh-lab-q/rpg/pull/196

**Comment by cibo94** [comment]
I don't think that problem is only in my commit (which hides the error) but that git can't find tag as you see in https://github.com/rh-lab-q/rpg/pull/195#issuecomment-118167779

**Comment by cibo94** [comment]
Yeah I know how to fix this ... we have to update or create new tag.

Update tag with latest commit:
```bash
git push origin :refs/tags/rpg-0.0.1-1
git tag -fa rpg-0.0.1-1
git push origin master --tags
```

On my branch this fixed it, but we need new tag on this repo.

**Comment by cibo94** [comment]
It is now working only on my branch but if you update tag it will work for everyone. [Here is build log](https://travis-ci.org/cibo94/rpg/builds/69430474)

**Comment by jsilhan** [comment]
I don't understand why should we replace the old tag. Why it suddenly breaks? Do we need to do it after another tito release too? I've made new release https://github.com/rh-lab-q/rpg/pull/196 and it doesn't work. Is the tito setup wrong? In your branch you have tagged a different commit. We cannot change release commits and force push.

**Comment by cibo94** [comment]
No I said that git describe can't find tag and I don't know why (maybe because there are a lot of changes since last tag). But updating tag fixed this issue as you can see in my fork.

Updating changes only commit of tag.

**Comment by jsilhan** [comment]
This was already merged along with my new release commit. Thanks

**Pull request closed without merging**
