### PR TITLE
build_rpm_recover is now general (fix #240)

### LINKED ISSUE #240: make `build_rpm_recover` more general
- [ ] add `mock_recover(self, logs (dict of Pathlib.Path log files), stdout, stderr, spec)` plugin method (/rpg/rpg/plugin.py). The method should return True (the spec file has changed) or False.
- [ ] call the `mock_recover` plugin methods from `build_rpm_recover` at the end of the loop. If any of the plugin method returns True, then continue, break otherwise
- [ ] In this issue move the bash command not found functionality to `rpg/plugins/recover/bash_command.py`.

### PR DESCRIPTION
**Pull request by cibo94**

### CODE REVIEW

**Comment by jsilhan** [comment]
Looks good. Do all local mock-tests pass?

**Comment by jsilhan** [comment]
@cibo94 , ^, can I merge it?

**Comment by cibo94** [comment]
Not yet I have to test it properly

**Comment by cibo94** [comment]
Now you may merge it. I had problem with mock tests, but all of them except ```mock_build/test_build_rpg.py``` are now passing.

**Comment by jsilhan** [comment]
do you know why `mock_build/test_build_rpg.py` is failing? When did the regression happen?

**Comment by cibo94** [comment]
I know why, RPG package that is used for that test, fails on ```make test```

**Comment by jsilhan** [comment]
Merged, thanks

**Pull request closed without merging**
